name:                th-serde
version:             0.1.0.0
github:              "axionbuster/th-serde"
license:             BSD-3-Clause
author:              "axionbuster"
maintainer:          "axionbuster@gmail.com"
copyright:           "2025 axionbuster"
category:            Development
synopsis:            A serialization/deserialization framework for Haskell

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/axionbuster/th-serde#readme>

language: GHC2021

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- LambdaCase
- QuasiQuotes
- RecordWildCards
- TemplateHaskell
- UndecidableInstances
- ViewPatterns

dependencies:
- base
- containers
- haskell-src-exts
- haskell-src-exts-simple
- haskell-src-meta
- megaparsec
- parser-combinators
- pretty-show
- template-haskell
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  th-serde-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - th-serde
