name:                macserde2
version:             0.1.0.0
github:              "githubuser/macserde2"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/macserde2#readme>

language: GHC2021

default-extensions:
- BlockArguments
- ViewPatterns
- LambdaCase
- TemplateHaskell

dependencies:
- base
- template-haskell
- transformers
- haskell-src-exts
- haskell-src-exts-simple
- haskell-src-meta
- megaparsec
- pretty-show
- parser-combinators

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  macserde2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - macserde2
