name:                th-serde
version:             0.1.2.2
github:              "axionbuster/th-serde"
license:             BSD-3-Clause
author:              "axionbuster"
maintainer:          "axionbuster@gmail.com"
copyright:           "2025 axionbuster"
category:            Development
synopsis:            A serialization/deserialization framework for Haskell

extra-source-files:
- README.md
- CHANGELOG.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
  A lightweight serialization/deserialization framework for Haskell that uses Template Haskell 
  and QuasiQuotes to separate data structure definitions from their serialization and validation 
  logic. It generates shadow types automatically and supports custom type class derivation 
  through coercion, reducing boilerplate while keeping business logic clean.

  For more information, please refer to the README.md file at
  <https://github.com/axionbuster/th-serde#readme>.

language: GHC2021

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- LambdaCase
- QuasiQuotes
- RecordWildCards
- TemplateHaskell
- UndecidableInstances
- ViewPatterns

# conservative with template-haskell due to
# frequent breaking changes

dependencies:
- base >= 4.19.0 && < 5
- containers >= 0.6.8 && < 0.7
- haskell-src-exts >= 1.23.1 && < 1.24
- haskell-src-exts-simple >= 1.23.1 && < 1.24
- haskell-src-meta >= 0.8.14 && < 0.9
- megaparsec >= 9.6.0 && < 10
- parser-combinators >= 1.3.0 && < 1.4
- pretty-show >= 1.10 && < 1.11
- template-haskell >= 2.21.0 && < 2.22
- transformers >= 0.6.1 && < 0.7

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  th-serde-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - th-serde
